### ISSUE TITLE
Add google docs apps to the blacklist by default

### ISSUE THREAD

**Issue by wilhelmmedetz** [VanCoding/One-Window#6]
For google docs apps it is possible to specify in the 'google apps launcher' wheter to start an app as a new tab or as a new window.

When opening a google docs app in a new window One-Window automatically tabifies it, thus overriding the google apps launcher options.

Would be nice if this could be added to the blacklist by default.

Alternatively - how can it be added to the blacklist manually?

**Comment by VanCoding** [comment]
Sadly there is no visual way of adding URLs to the blacklist since I'm not the developer of the blacklist feature.

But you can do it manually by going to the extensions section in the crhome settings and clicking on the  "Background Page" button of the One Window extension. This opens a debugger window. If you switch to the console table, you can execute code.

Executing the following code would blacklist all URLs starting with "http://google.com"
```
var blacklist = JSON.parse(localStorage["blacklist"])
blacklist.push("^http://google.com");
localStorage = JSON.stringify(blacklist);
```

You can modify it to match your needs.

**Comment by VanCoding** [comment]
I think I'm not going to maintain a list of URLs that should be blacklisted by default. I'd rather make a visual blacklist editor, so the user can blacklist individually.

Closing this.
